### ISSUE TITLE
userscript breaks when clicking on the icon from any tab other than the overview

### ISSUE THREAD

**Issue by quantenzitrone** [Lioncat6/MusicBrainz-UserScripts#1]
e.g. clicking on the button when in the "Releases" tab, it opens `https://lioncat6.github.io/SAMBL/artist/?spid=0dE2azLipjakJifWO2xrOO&artist_mbid=releases`

**Comment by Lioncat6** [comment]
Oh, sorry lol
Didn't see you made a fix

**Comment by Lioncat6** [comment]
Thanks for actually using the script, though.

Greasyfork should push the update in a few seconds
