### ISSUE TITLE
URL parameters included

### ISSUE THREAD

**Issue by nimuxoha** [Lioncat6/MusicBrainz-UserScripts#3]
When there are URL parameters they will be sent to SAMBL leading to an error: `Musicbrainz artist not found. URL likely malfomed`

A possible solution would be changing 
`let mbid = document.location.href.split("/artist/")[1].split("/")[0];`
to
`let mbid = document.location.pathname.split("/artist/")[1].split("/")[0];` [which omits the URL parameters](https://developer.mozilla.org/en-US/docs/Web/API/Location/pathname) (query string)

**Comment by Lioncat6** [comment]
https://github.com/Lioncat6/MusicBrainz-UserScripts/commit/8f0994dd937a3e5d9be80041d1c04fed1ebbf05f
